// D-031 (Francesco, 6 ott 2026) e D-040 (Enrico, 7 ott 2026): domanda sulle condizioni ad alto rischio.
// La lista e i testi del blocco sono quelli di Francesco (DECISIONI_LANCIO_FRANCESCO_2026_10_06.md).
// D-043 (3): domanda, sottotitolo e risposte approvati da Francesco (IT/EN, 7 ott 2026); le altre 8 lingue
// tradotte dall'inglese approvato, da QA linguistico. La lista si mostra; al backend arriva solo sì/no.
// Lingue diverse da italiano e inglese: traduzioni della Regia, da far rileggere prima del lancio.

export const HIGH_RISK_SCREENING_VERSION = "HIGH_RISK_V1";

// Stesso ordine e stesse chiavi di dubi-backend config/high-risk-screening.js.
export const HIGH_RISK_CONDITION_KEYS = Object.freeze([
  "pregnancy_or_breastfeeding",
  "insulin_treated_diabetes_or_severe_hypoglycaemia",
  "chronic_kidney_disease_dialysis_transplant_or_renal_restriction",
  "eating_disorder_active_suspected_or_recent_treatment",
  "bariatric_surgery_with_follow_up",
  "cancer_in_active_treatment_or_cachexia_risk",
  "advanced_liver_disease",
  "heart_failure_or_prescribed_fluid_sodium_electrolyte_protein_restriction",
  "prescribed_therapeutic_diet",
  "food_anaphylaxis_or_multiple_severe_allergies",
  "rapid_unexplained_weight_loss",
]);

// Codici del backend che impediscono il piano: l'app mostra una schermata dedicata, mai un piano.
// D-032 / D-058 (Francesco, 9 ott 2026): per i 14–17 anni nessun piano automatico (MINOR_CLINICAL_PLAN_REQUIRED).
// Testi del blocco minorenni: della Regia (IT/EN), da far rivedere alla sezione 5; altre 8 lingue da QA linguistico.
export const PLAN_BLOCKING_CODES = Object.freeze([
  "HIGH_RISK_SCREENING_REQUIRED",
  "HEALTH_PLAN_BLOCKED",
  "GOAL_UNSAFE_FOR_BMI",
  "MINOR_CLINICAL_PLAN_REQUIRED",
]);

export function planBlockingCode(payload) {
  const code = payload && typeof payload.error === "string" ? payload.error : null;
  return PLAN_BLOCKING_CODES.includes(code) ? code : null;
}

// Corpo della richiesta: solo il booleano e la versione (D-040). Risposta esplicita "no" o "yes",
// mai dedotta: qualsiasi altro valore è un errore.
export const HIGH_RISK_ANSWERS = Object.freeze(["no", "yes"]);
export function highRiskAnswerBody(answer) {
  if (answer === null || answer === undefined || answer === "") throw new Error("HIGH_RISK_ANSWER_MISSING");
  if (!HIGH_RISK_ANSWERS.includes(answer)) throw new Error("HIGH_RISK_ANSWER_INVALID");
  return { has_high_risk_condition: answer === "yes", screening_version: HIGH_RISK_SCREENING_VERSION };
}

const IT = {
  title: "Prima di creare il tuo piano",
  question: "Hai una delle seguenti condizioni oppure segui una dieta terapeutica prescritta da un medico o dietista?",
  subtitle: "Se rispondi sì, per la tua sicurezza DUBI non genererà automaticamente calorie, macro o piano alimentare.",
  privacy: "DUBI salva solo la risposta sì/no, non quale condizione.",
  conditions: {
    pregnancy_or_breastfeeding: "Gravidanza o allattamento",
    insulin_treated_diabetes_or_severe_hypoglycaemia: "Diabete trattato con insulina, oppure ipoglicemie ricorrenti o severe",
    chronic_kidney_disease_dialysis_transplant_or_renal_restriction: "Malattia renale cronica, dialisi, trapianto di rene o restrizione renale prescritta",
    eating_disorder_active_suspected_or_recent_treatment: "Disturbo del comportamento alimentare in corso o sospetto, o trattamento specialistico recente",
    bariatric_surgery_with_follow_up: "Chirurgia bariatrica con controlli specialistici in corso",
    cancer_in_active_treatment_or_cachexia_risk: "Tumore in trattamento, o rischio di cachessia o malnutrizione",
    advanced_liver_disease: "Malattia del fegato avanzata o scompensata",
    heart_failure_or_prescribed_fluid_sodium_electrolyte_protein_restriction: "Scompenso cardiaco, o restrizioni prescritte di liquidi, sodio, elettroliti o proteine",
    prescribed_therapeutic_diet: "Una dieta terapeutica prescritta da un medico o da un dietista",
    food_anaphylaxis_or_multiple_severe_allergies: "Anafilassi alimentare in passato, o più allergie alimentari gravi",
    rapid_unexplained_weight_loss: "Perdita di peso rapida e senza una causa nota",
  },
  answerNo: "No, nessuna di queste condizioni",
  answerYes: "Sì, una o più condizioni",
  confirm: "Conferma",
  saving: "Salvataggio...",
  required: "Scegli una risposta per continuare.",
  error: "Non riesco a salvare la risposta. Controlla la connessione e riprova.",
  settingsLabel: "Condizioni di salute che richiedono un professionista",
  settingsSub: "Aggiorna la risposta se la tua situazione cambia.",
  blockTitle: "Per la tua sicurezza, DUBI non può generare automaticamente il piano.",
  blockBody: "Hai indicato una condizione che richiede una valutazione individuale da parte di un medico o dietista. DUBI non modifica terapie, farmaci o restrizioni cliniche.",
  blockNext: "Parlane con il professionista che ti segue. Con indicazioni cliniche specifiche, DUBI potrà essere usato solo come supporto organizzativo.",
  blockAck: "Ho capito",
  blockChange: "La mia situazione è cambiata",
  bmiTitle: "Con il tuo peso attuale DUBI non può creare un piano per questo obiettivo.",
  bmiBody: "Con il BMI che risulta dai tuoi dati, un deficit calorico non è indicato. Puoi scegliere mantenimento o aumento di massa; ti consigliamo una valutazione con un medico o un dietista.",
  bmiLowBody: "Con il peso e l'altezza che hai indicato il BMI risulta sotto 17. In questa situazione serve una valutazione individuale da parte di un medico o dietista prima di qualsiasi piano alimentare.",
  minorTitle: "Per ora DUBI non crea un piano alimentare automatico per chi ha meno di 18 anni.",
  minorBody: "Alla tua età il corpo è ancora in crescita e calorie e porzioni vanno valutate in modo diverso rispetto agli adulti. Stiamo preparando una versione pensata per i ragazzi: fino ad allora DUBI non calcola calorie, macro né un piano.",
  minorNext: "Se vuoi un piano alimentare adesso, parlane con il pediatra o con un nutrizionista.",
  bmiChange: "Cambia obiettivo",
};

const EN = {
  title: "Before we create your plan",
  question: "Do you have any of the following conditions, or are you following a therapeutic diet prescribed by a doctor or registered dietitian?",
  subtitle: "If you answer yes, DUBI will not automatically generate calories, macros or a meal plan.",
  privacy: "DUBI only stores a yes/no answer, never which condition.",
  conditions: {
    pregnancy_or_breastfeeding: "Pregnancy or breastfeeding",
    insulin_treated_diabetes_or_severe_hypoglycaemia: "Diabetes treated with insulin, or recurrent or severe hypoglycaemia",
    chronic_kidney_disease_dialysis_transplant_or_renal_restriction: "Chronic kidney disease, dialysis, kidney transplant or a prescribed renal restriction",
    eating_disorder_active_suspected_or_recent_treatment: "An eating disorder that is active or suspected, or recent specialist treatment",
    bariatric_surgery_with_follow_up: "Bariatric surgery with ongoing specialist follow-up",
    cancer_in_active_treatment_or_cachexia_risk: "Cancer in active treatment, or risk of cachexia or malnutrition",
    advanced_liver_disease: "Advanced or decompensated liver disease",
    heart_failure_or_prescribed_fluid_sodium_electrolyte_protein_restriction: "Heart failure, or prescribed restrictions on fluids, sodium, electrolytes or protein",
    prescribed_therapeutic_diet: "A therapeutic diet prescribed by a doctor or registered dietitian",
    food_anaphylaxis_or_multiple_severe_allergies: "Past food anaphylaxis, or several severe food allergies",
    rapid_unexplained_weight_loss: "Rapid weight loss without a known cause",
  },
  answerNo: "No, none of these conditions",
  answerYes: "Yes, one or more conditions",
  confirm: "Confirm",
  saving: "Saving...",
  required: "Choose an answer to continue.",
  error: "We couldn't save your answer. Check your connection and try again.",
  settingsLabel: "Health conditions that need a professional",
  settingsSub: "Update your answer if your situation changes.",
  blockTitle: "For your safety, DUBI cannot generate an automatic plan.",
  blockBody: "You reported a condition that requires an individual assessment by a doctor or registered dietitian. DUBI does not change treatments, medication or clinical restrictions.",
  blockNext: "Please speak with the clinician supporting you. With specific clinical instructions, DUBI may only be used as an organisational aid.",
  blockAck: "I understand",
  blockChange: "My situation has changed",
  bmiTitle: "At your current weight DUBI cannot create a plan for this goal.",
  bmiBody: "With the BMI from your details, a calorie deficit is not appropriate. You can choose maintenance or muscle gain; we recommend an assessment with a doctor or registered dietitian.",
  bmiLowBody: "With the weight and height you entered, your BMI is below 17. In this situation an individual assessment by a doctor or registered dietitian is needed before any meal plan.",
  minorTitle: "For now, DUBI does not create an automatic meal plan for anyone under 18.",
  minorBody: "At your age your body is still growing, so calories and portions need to be assessed differently from adults. We are preparing a version designed for teenagers: until then DUBI does not calculate calories, macros or a plan.",
  minorNext: "If you want a meal plan now, talk to your paediatrician or a nutrition professional.",
  bmiChange: "Change goal",
};

const FR = {
  title: "Avant de créer ton plan",
  question: "As-tu l'une des conditions suivantes, ou suis-tu un régime thérapeutique prescrit par un médecin ou un diététicien ?",
  subtitle: "Si tu réponds oui, DUBI ne générera pas automatiquement de calories, de macros ni de plan alimentaire.",
  privacy: "DUBI n'enregistre qu'une réponse oui/non, jamais la condition.",
  conditions: {
    pregnancy_or_breastfeeding: "Grossesse ou allaitement",
    insulin_treated_diabetes_or_severe_hypoglycaemia: "Diabète traité par insuline, ou hypoglycémies récurrentes ou sévères",
    chronic_kidney_disease_dialysis_transplant_or_renal_restriction: "Maladie rénale chronique, dialyse, greffe de rein ou restriction rénale prescrite",
    eating_disorder_active_suspected_or_recent_treatment: "Trouble du comportement alimentaire actif ou suspecté, ou traitement spécialisé récent",
    bariatric_surgery_with_follow_up: "Chirurgie bariatrique avec suivi spécialisé en cours",
    cancer_in_active_treatment_or_cachexia_risk: "Cancer en cours de traitement, ou risque de cachexie ou de dénutrition",
    advanced_liver_disease: "Maladie du foie avancée ou décompensée",
    heart_failure_or_prescribed_fluid_sodium_electrolyte_protein_restriction: "Insuffisance cardiaque, ou restrictions prescrites de liquides, sodium, électrolytes ou protéines",
    prescribed_therapeutic_diet: "Un régime thérapeutique prescrit par un médecin ou un diététicien",
    food_anaphylaxis_or_multiple_severe_allergies: "Anaphylaxie alimentaire passée, ou plusieurs allergies alimentaires graves",
    rapid_unexplained_weight_loss: "Perte de poids rapide sans cause connue",
  },
  answerNo: "Non, aucune de ces conditions",
  answerYes: "Oui, une ou plusieurs conditions",
  confirm: "Confirmer",
  saving: "Enregistrement...",
  required: "Choisis une réponse pour continuer.",
  error: "Impossible d'enregistrer ta réponse. Vérifie ta connexion et réessaie.",
  settingsLabel: "Conditions de santé nécessitant un professionnel",
  settingsSub: "Mets à jour ta réponse si ta situation change.",
  blockTitle: "Pour ta sécurité, DUBI ne peut pas générer de plan automatique.",
  blockBody: "Tu as indiqué une condition qui nécessite une évaluation individuelle par un médecin ou un diététicien. DUBI ne modifie ni traitements, ni médicaments, ni restrictions cliniques.",
  blockNext: "Parles-en au professionnel qui te suit. Avec des indications cliniques précises, DUBI ne pourra servir que d'aide à l'organisation.",
  blockAck: "J'ai compris",
  blockChange: "Ma situation a changé",
  bmiTitle: "Avec ton poids actuel, DUBI ne peut pas créer de plan pour cet objectif.",
  bmiBody: "Avec l'IMC calculé à partir de tes données, un déficit calorique n'est pas indiqué. Tu peux choisir maintien ou prise de masse ; nous te conseillons un avis médical ou diététique.",
  bmiLowBody: "Avec le poids et la taille indiqués, ton IMC est inférieur à 17. Dans ce cas, une évaluation individuelle par un médecin ou un diététicien est nécessaire avant tout plan alimentaire.",
  minorTitle: "Pour l'instant, DUBI ne crée pas de plan alimentaire automatique pour les moins de 18 ans.",
  minorBody: "À ton âge, ton corps est encore en croissance : les calories et les portions doivent être évaluées différemment de celles des adultes. Nous préparons une version pensée pour les adolescents ; d'ici là, DUBI ne calcule ni calories, ni macros, ni plan.",
  minorNext: "Si tu veux un plan alimentaire maintenant, parles-en à ton pédiatre ou à un professionnel de la nutrition.",
  bmiChange: "Changer d'objectif",
};

const ES = {
  title: "Antes de crear tu plan",
  question: "¿Tienes alguna de las siguientes condiciones o sigues una dieta terapéutica prescrita por un médico o dietista?",
  subtitle: "Si respondes que sí, DUBI no generará automáticamente calorías, macros ni un plan de alimentación.",
  privacy: "DUBI solo guarda una respuesta sí/no, nunca cuál es la condición.",
  conditions: {
    pregnancy_or_breastfeeding: "Embarazo o lactancia",
    insulin_treated_diabetes_or_severe_hypoglycaemia: "Diabetes tratada con insulina, o hipoglucemias recurrentes o graves",
    chronic_kidney_disease_dialysis_transplant_or_renal_restriction: "Enfermedad renal crónica, diálisis, trasplante de riñón o restricción renal prescrita",
    eating_disorder_active_suspected_or_recent_treatment: "Trastorno de la conducta alimentaria activo o sospechado, o tratamiento especializado reciente",
    bariatric_surgery_with_follow_up: "Cirugía bariátrica con seguimiento especializado en curso",
    cancer_in_active_treatment_or_cachexia_risk: "Cáncer en tratamiento, o riesgo de caquexia o desnutrición",
    advanced_liver_disease: "Enfermedad hepática avanzada o descompensada",
    heart_failure_or_prescribed_fluid_sodium_electrolyte_protein_restriction: "Insuficiencia cardíaca, o restricciones prescritas de líquidos, sodio, electrolitos o proteínas",
    prescribed_therapeutic_diet: "Una dieta terapéutica prescrita por un médico o dietista",
    food_anaphylaxis_or_multiple_severe_allergies: "Anafilaxia alimentaria previa, o varias alergias alimentarias graves",
    rapid_unexplained_weight_loss: "Pérdida de peso rápida sin causa conocida",
  },
  answerNo: "No, ninguna de estas condiciones",
  answerYes: "Sí, una o más condiciones",
  confirm: "Confirmar",
  saving: "Guardando...",
  required: "Elige una respuesta para continuar.",
  error: "No se pudo guardar tu respuesta. Revisa la conexión e inténtalo de nuevo.",
  settingsLabel: "Condiciones de salud que requieren un profesional",
  settingsSub: "Actualiza tu respuesta si tu situación cambia.",
  blockTitle: "Por tu seguridad, DUBI no puede generar un plan automático.",
  blockBody: "Has indicado una condición que requiere una valoración individual por parte de un médico o dietista. DUBI no modifica tratamientos, medicamentos ni restricciones clínicas.",
  blockNext: "Háblalo con el profesional que te sigue. Con indicaciones clínicas específicas, DUBI solo podrá usarse como apoyo organizativo.",
  blockAck: "Entendido",
  blockChange: "Mi situación ha cambiado",
  bmiTitle: "Con tu peso actual, DUBI no puede crear un plan para este objetivo.",
  bmiBody: "Con el IMC que resulta de tus datos, un déficit calórico no está indicado. Puedes elegir mantenimiento o ganancia muscular; te recomendamos una valoración con un médico o dietista.",
  bmiLowBody: "Con el peso y la altura que has indicado, tu IMC es inferior a 17. En esta situación se necesita una valoración individual de un médico o dietista antes de cualquier plan de alimentación.",
  minorTitle: "Por ahora, DUBI no crea un plan de alimentación automático para menores de 18 años.",
  minorBody: "A tu edad tu cuerpo todavía está creciendo: las calorías y las porciones deben valorarse de forma distinta a las de los adultos. Estamos preparando una versión pensada para adolescentes; hasta entonces, DUBI no calcula calorías, macros ni un plan.",
  minorNext: "Si quieres un plan de alimentación ahora, habla con tu pediatra o con un profesional de la nutrición.",
  bmiChange: "Cambiar objetivo",
};

const DE = {
  title: "Bevor wir deinen Plan erstellen",
  question: "Trifft einer der folgenden Punkte auf dich zu, oder folgst du einer therapeutischen Diät, die dir ein Arzt oder eine Ernährungsfachkraft verordnet hat?",
  subtitle: "Wenn du mit Ja antwortest, erstellt DUBI nicht automatisch Kalorien, Makros oder einen Ernährungsplan.",
  privacy: "DUBI speichert nur Ja/Nein, nie welcher Punkt.",
  conditions: {
    pregnancy_or_breastfeeding: "Schwangerschaft oder Stillzeit",
    insulin_treated_diabetes_or_severe_hypoglycaemia: "Mit Insulin behandelter Diabetes oder wiederkehrende bzw. schwere Unterzuckerungen",
    chronic_kidney_disease_dialysis_transplant_or_renal_restriction: "Chronische Nierenerkrankung, Dialyse, Nierentransplantation oder verordnete Nierendiät",
    eating_disorder_active_suspected_or_recent_treatment: "Aktive oder vermutete Essstörung oder kürzliche fachärztliche Behandlung",
    bariatric_surgery_with_follow_up: "Adipositaschirurgie mit laufender fachärztlicher Nachsorge",
    cancer_in_active_treatment_or_cachexia_risk: "Krebs in Behandlung oder Risiko für Kachexie bzw. Mangelernährung",
    advanced_liver_disease: "Fortgeschrittene oder dekompensierte Lebererkrankung",
    heart_failure_or_prescribed_fluid_sodium_electrolyte_protein_restriction: "Herzinsuffizienz oder verordnete Beschränkungen von Flüssigkeit, Natrium, Elektrolyten oder Eiweiß",
    prescribed_therapeutic_diet: "Eine von Arzt oder Diätassistenz verordnete therapeutische Diät",
    food_anaphylaxis_or_multiple_severe_allergies: "Frühere Nahrungsmittel-Anaphylaxie oder mehrere schwere Nahrungsmittelallergien",
    rapid_unexplained_weight_loss: "Schneller Gewichtsverlust ohne bekannte Ursache",
  },
  answerNo: "Nein, nichts davon",
  answerYes: "Ja, einer oder mehrere Punkte",
  confirm: "Bestätigen",
  saving: "Wird gespeichert...",
  required: "Wähle eine Antwort, um fortzufahren.",
  error: "Deine Antwort konnte nicht gespeichert werden. Prüfe die Verbindung und versuche es erneut.",
  settingsLabel: "Gesundheitszustände, die eine Fachperson erfordern",
  settingsSub: "Aktualisiere deine Antwort, wenn sich deine Situation ändert.",
  blockTitle: "Zu deiner Sicherheit kann DUBI keinen automatischen Plan erstellen.",
  blockBody: "Du hast einen Zustand angegeben, der eine individuelle Beurteilung durch Arzt oder Diätassistenz erfordert. DUBI ändert keine Therapien, Medikamente oder klinischen Einschränkungen.",
  blockNext: "Sprich mit der Fachperson, die dich betreut. Mit konkreten klinischen Vorgaben kann DUBI nur als organisatorische Hilfe genutzt werden.",
  blockAck: "Verstanden",
  blockChange: "Meine Situation hat sich geändert",
  bmiTitle: "Mit deinem aktuellen Gewicht kann DUBI für dieses Ziel keinen Plan erstellen.",
  bmiBody: "Bei dem BMI aus deinen Angaben ist ein Kaloriendefizit nicht angezeigt. Du kannst Gewicht halten oder Muskelaufbau wählen; wir empfehlen eine ärztliche oder diätetische Beurteilung.",
  bmiLowBody: "Mit dem angegebenen Gewicht und der Größe liegt dein BMI unter 17. In dieser Situation ist vor jedem Ernährungsplan eine individuelle Beurteilung durch Arzt oder Diätassistenz nötig.",
  minorTitle: "DUBI erstellt derzeit keinen automatischen Ernährungsplan für Personen unter 18 Jahren.",
  minorBody: "In deinem Alter wächst dein Körper noch: Kalorien und Portionen müssen anders beurteilt werden als bei Erwachsenen. Wir bereiten eine Version für Jugendliche vor; bis dahin berechnet DUBI keine Kalorien, Makros und keinen Plan.",
  minorNext: "Wenn du jetzt einen Ernährungsplan möchtest, sprich mit deiner Kinderärztin, deinem Kinderarzt oder einer Ernährungsfachkraft.",
  bmiChange: "Ziel ändern",
};

const AR = {
  title: "قبل إنشاء خطتك",
  question: "هل لديك أي من الحالات التالية، أو تتبع نظامًا غذائيًا علاجيًا وصفه لك طبيب أو أخصائي تغذية؟",
  subtitle: "إذا أجبت بنعم، فلن يُنشئ DUBI تلقائيًا السعرات الحرارية أو المغذيات الكبرى أو خطة الوجبات.",
  privacy: "يحفظ DUBI إجابة نعم/لا فقط، ولا يحفظ الحالة نفسها.",
  conditions: {
    pregnancy_or_breastfeeding: "الحمل أو الرضاعة الطبيعية",
    insulin_treated_diabetes_or_severe_hypoglycaemia: "سكري يُعالج بالإنسولين، أو نوبات هبوط سكر متكررة أو شديدة",
    chronic_kidney_disease_dialysis_transplant_or_renal_restriction: "مرض كلوي مزمن أو غسيل كلى أو زراعة كلية أو قيود كلوية موصوفة",
    eating_disorder_active_suspected_or_recent_treatment: "اضطراب أكل نشط أو مشتبه به، أو علاج متخصص حديث",
    bariatric_surgery_with_follow_up: "جراحة السمنة مع متابعة متخصصة مستمرة",
    cancer_in_active_treatment_or_cachexia_risk: "سرطان قيد العلاج، أو خطر الدنف أو سوء التغذية",
    advanced_liver_disease: "مرض كبدي متقدم أو غير معاوض",
    heart_failure_or_prescribed_fluid_sodium_electrolyte_protein_restriction: "قصور القلب، أو قيود موصوفة على السوائل أو الصوديوم أو الأملاح أو البروتين",
    prescribed_therapeutic_diet: "نظام غذائي علاجي موصوف من طبيب أو أخصائي تغذية",
    food_anaphylaxis_or_multiple_severe_allergies: "تأق غذائي سابق، أو عدة أنواع من الحساسية الغذائية الشديدة",
    rapid_unexplained_weight_loss: "فقدان سريع للوزن دون سبب معروف",
  },
  answerNo: "لا، لا توجد أي من هذه الحالات",
  answerYes: "نعم، حالة واحدة أو أكثر",
  confirm: "تأكيد",
  saving: "جارٍ الحفظ...",
  required: "اختر إجابة للمتابعة.",
  error: "تعذّر حفظ إجابتك. تحقق من الاتصال وحاول مرة أخرى.",
  settingsLabel: "حالات صحية تحتاج إلى مختص",
  settingsSub: "حدّث إجابتك إذا تغيّر وضعك.",
  blockTitle: "حفاظًا على سلامتك، لا يمكن لـ DUBI إنشاء خطة تلقائية.",
  blockBody: "أشرت إلى حالة تتطلب تقييمًا فرديًا من طبيب أو أخصائي تغذية. لا يغيّر DUBI العلاجات أو الأدوية أو القيود السريرية.",
  blockNext: "تحدّث مع المختص الذي يتابعك. مع تعليمات سريرية محددة، يمكن استخدام DUBI كأداة تنظيمية فقط.",
  blockAck: "فهمت",
  blockChange: "تغيّر وضعي",
  bmiTitle: "بوزنك الحالي لا يمكن لـ DUBI إنشاء خطة لهذا الهدف.",
  bmiBody: "مع مؤشر كتلة الجسم الناتج عن بياناتك، لا يُنصح بعجز في السعرات. يمكنك اختيار الحفاظ على الوزن أو زيادة الكتلة العضلية، وننصح بتقييم من طبيب أو أخصائي تغذية.",
  bmiLowBody: "وفقًا للوزن والطول اللذين أدخلتهما، فإن مؤشر كتلة جسمك أقل من 17. في هذه الحالة يلزم تقييم فردي من طبيب أو أخصائي تغذية قبل أي خطة غذائية.",
  minorTitle: "حاليًا، لا ينشئ DUBI خطة غذائية تلقائية لمن هم دون 18 عامًا.",
  minorBody: "في عمرك لا يزال جسمك في طور النمو، لذلك يجب تقييم السعرات الحرارية والحصص بطريقة مختلفة عن البالغين. نعمل على إعداد نسخة مخصصة للمراهقين؛ وحتى ذلك الحين لا يحسب DUBI السعرات الحرارية أو العناصر الغذائية الكبرى ولا ينشئ خطة.",
  minorNext: "إذا كنت تريد خطة غذائية الآن، فتحدث مع طبيب الأطفال أو مع أخصائي تغذية.",
  bmiChange: "تغيير الهدف",
};

const PT = {
  title: "Antes de criarmos o teu plano",
  question: "Tens alguma das seguintes condições, ou segues uma dieta terapêutica prescrita por um médico ou nutricionista?",
  subtitle: "Se responderes sim, a DUBI não vai gerar automaticamente calorias, macros nem um plano alimentar.",
  privacy: "A DUBI guarda apenas uma resposta sim/não, nunca qual é a condição.",
  conditions: {
    pregnancy_or_breastfeeding: "Gravidez ou amamentação",
    insulin_treated_diabetes_or_severe_hypoglycaemia: "Diabetes tratada com insulina, ou hipoglicemias recorrentes ou graves",
    chronic_kidney_disease_dialysis_transplant_or_renal_restriction: "Doença renal crónica, diálise, transplante renal ou restrição renal prescrita",
    eating_disorder_active_suspected_or_recent_treatment: "Perturbação do comportamento alimentar ativa ou suspeita, ou tratamento especializado recente",
    bariatric_surgery_with_follow_up: "Cirurgia bariátrica com acompanhamento especializado em curso",
    cancer_in_active_treatment_or_cachexia_risk: "Cancro em tratamento, ou risco de caquexia ou desnutrição",
    advanced_liver_disease: "Doença hepática avançada ou descompensada",
    heart_failure_or_prescribed_fluid_sodium_electrolyte_protein_restriction: "Insuficiência cardíaca, ou restrições prescritas de líquidos, sódio, eletrólitos ou proteínas",
    prescribed_therapeutic_diet: "Uma dieta terapêutica prescrita por um médico ou nutricionista",
    food_anaphylaxis_or_multiple_severe_allergies: "Anafilaxia alimentar no passado, ou várias alergias alimentares graves",
    rapid_unexplained_weight_loss: "Perda de peso rápida sem causa conhecida",
  },
  answerNo: "Não, nenhuma destas condições",
  answerYes: "Sim, uma ou mais condições",
  confirm: "Confirmar",
  saving: "A guardar...",
  required: "Escolhe uma resposta para continuar.",
  error: "Não foi possível guardar a tua resposta. Verifica a ligação e tenta novamente.",
  settingsLabel: "Condições de saúde que requerem um profissional",
  settingsSub: "Atualiza a tua resposta se a tua situação mudar.",
  blockTitle: "Para tua segurança, a DUBI não pode gerar um plano automático.",
  blockBody: "Indicaste uma condição que requer uma avaliação individual por um médico ou nutricionista. A DUBI não altera tratamentos, medicamentos ou restrições clínicas.",
  blockNext: "Fala com o profissional que te acompanha. Com indicações clínicas específicas, a DUBI só poderá ser usada como apoio organizativo.",
  blockAck: "Compreendi",
  blockChange: "A minha situação mudou",
  bmiTitle: "Com o teu peso atual, a DUBI não pode criar um plano para este objetivo.",
  bmiBody: "Com o IMC que resulta dos teus dados, um défice calórico não é indicado. Podes escolher manutenção ou ganho muscular; recomendamos uma avaliação com um médico ou nutricionista.",
  bmiLowBody: "Com o peso e a altura que indicaste, o teu IMC é inferior a 17. Nesta situação é necessária uma avaliação individual por um médico ou nutricionista antes de qualquer plano alimentar.",
  minorTitle: "Por agora, a DUBI não cria um plano alimentar automático para menores de 18 anos.",
  minorBody: "Na tua idade o teu corpo ainda está a crescer: as calorias e as porções têm de ser avaliadas de forma diferente das dos adultos. Estamos a preparar uma versão pensada para adolescentes; até lá, a DUBI não calcula calorias, macros nem um plano.",
  minorNext: "Se quiseres um plano alimentar agora, fala com o teu pediatra ou com um profissional de nutrição.",
  bmiChange: "Mudar objetivo",
};

const ZH = {
  title: "在生成你的计划之前",
  question: "你是否有以下任何一种情况，或正在遵循医生或注册营养师开具的治疗性饮食？",
  subtitle: "如果你回答“是”，DUBI 将不会自动生成热量、宏量营养素或饮食计划。",
  privacy: "DUBI 只保存“是/否”的回答，不保存具体是哪种情况。",
  conditions: {
    pregnancy_or_breastfeeding: "怀孕或哺乳期",
    insulin_treated_diabetes_or_severe_hypoglycaemia: "使用胰岛素治疗的糖尿病，或反复/严重低血糖",
    chronic_kidney_disease_dialysis_transplant_or_renal_restriction: "慢性肾病、透析、肾移植或医嘱肾脏饮食限制",
    eating_disorder_active_suspected_or_recent_treatment: "正在发生或疑似的进食障碍，或近期接受过专科治疗",
    bariatric_surgery_with_follow_up: "减重手术后仍在专科随访",
    cancer_in_active_treatment_or_cachexia_risk: "正在治疗的癌症，或有恶病质/营养不良风险",
    advanced_liver_disease: "晚期或失代偿期肝病",
    heart_failure_or_prescribed_fluid_sodium_electrolyte_protein_restriction: "心力衰竭，或医嘱限制液体、钠、电解质或蛋白质",
    prescribed_therapeutic_diet: "由医生或营养师开具的治疗性饮食",
    food_anaphylaxis_or_multiple_severe_allergies: "曾发生食物过敏性休克，或有多种严重食物过敏",
    rapid_unexplained_weight_loss: "原因不明的快速体重下降",
  },
  answerNo: "否，以上情况都没有",
  answerYes: "是，有一种或多种情况",
  confirm: "确认",
  saving: "正在保存...",
  required: "请选择一个回答以继续。",
  error: "无法保存你的回答。请检查网络后重试。",
  settingsLabel: "需要专业人士评估的健康状况",
  settingsSub: "如果你的情况发生变化，请更新回答。",
  blockTitle: "为了你的安全，DUBI 无法自动生成计划。",
  blockBody: "你提到的情况需要由医生或注册营养师进行个体评估。DUBI 不会更改治疗、药物或临床限制。",
  blockNext: "请与正在为你提供照护的专业人士沟通。在有明确临床指示的情况下，DUBI 只能作为日常安排的辅助工具。",
  blockAck: "我明白了",
  blockChange: "我的情况已经改变",
  bmiTitle: "以你目前的体重，DUBI 无法为这个目标生成计划。",
  bmiBody: "根据你的数据计算出的 BMI，不适合热量缺口。你可以选择保持体重或增肌；建议咨询医生或注册营养师。",
  bmiLowBody: "根据你填写的体重和身高，你的 BMI 低于 17。在这种情况下，任何饮食计划之前都需要由医生或注册营养师进行个体评估。",
  minorTitle: "目前，DUBI 不为未满 18 岁的用户自动生成饮食计划。",
  minorBody: "在你这个年龄，身体仍在生长，热量和份量需要以不同于成年人的方式评估。我们正在准备专为青少年设计的版本；在此之前，DUBI 不计算热量、宏量营养素，也不生成计划。",
  minorNext: "如果你现在需要饮食计划，请咨询儿科医生或营养专业人士。",
  bmiChange: "更改目标",
};

const JA = {
  title: "プランを作成する前に",
  question: "次のいずれかに当てはまりますか？または、医師や管理栄養士から処方された治療食を続けていますか？",
  subtitle: "「はい」と答えた場合、DUBIはカロリー、マクロ栄養素、食事プランを自動で作成しません。",
  privacy: "DUBIが保存するのは「はい/いいえ」の回答だけで、どの項目かは保存しません。",
  conditions: {
    pregnancy_or_breastfeeding: "妊娠中または授乳中",
    insulin_treated_diabetes_or_severe_hypoglycaemia: "インスリン治療中の糖尿病、または繰り返す・重い低血糖",
    chronic_kidney_disease_dialysis_transplant_or_renal_restriction: "慢性腎臓病、透析、腎移植、または医師に指示された腎臓の食事制限",
    eating_disorder_active_suspected_or_recent_treatment: "現在の、または疑いのある摂食障害、または最近の専門治療",
    bariatric_surgery_with_follow_up: "専門医の経過観察中の減量手術後",
    cancer_in_active_treatment_or_cachexia_risk: "治療中のがん、または悪液質・低栄養のリスク",
    advanced_liver_disease: "進行した、または非代償性の肝疾患",
    heart_failure_or_prescribed_fluid_sodium_electrolyte_protein_restriction: "心不全、または医師に指示された水分・ナトリウム・電解質・たんぱく質の制限",
    prescribed_therapeutic_diet: "医師または管理栄養士が処方した治療食",
    food_anaphylaxis_or_multiple_severe_allergies: "過去の食物アナフィラキシー、または複数の重い食物アレルギー",
    rapid_unexplained_weight_loss: "原因不明の急激な体重減少",
  },
  answerNo: "いいえ、どれにも当てはまりません",
  answerYes: "はい、1つ以上当てはまります",
  confirm: "確認",
  saving: "保存中...",
  required: "続けるには回答を選んでください。",
  error: "回答を保存できませんでした。接続を確認して、もう一度お試しください。",
  settingsLabel: "専門家の判断が必要な健康状態",
  settingsSub: "状況が変わったら回答を更新してください。",
  blockTitle: "安全のため、DUBIは自動でプランを作成できません。",
  blockBody: "医師または管理栄養士による個別の評価が必要な状態が報告されました。DUBIは治療、薬、臨床上の制限を変更しません。",
  blockNext: "担当の専門家に相談してください。具体的な臨床上の指示がある場合、DUBIは日々の管理の補助としてのみ利用できます。",
  blockAck: "わかりました",
  blockChange: "状況が変わりました",
  bmiTitle: "現在の体重では、DUBIはこの目標のプランを作成できません。",
  bmiBody: "入力データから算出したBMIでは、カロリー不足は適していません。体重維持または筋肉増量を選べます。医師または管理栄養士による評価をおすすめします。",
  bmiLowBody: "入力された体重と身長では、BMIが17未満です。この場合、食事プランの前に医師または管理栄養士による個別の評価が必要です。",
  minorTitle: "現在、DUBIは18歳未満の方向けに自動で食事プランを作成しません。",
  minorBody: "あなたの年齢では体はまだ成長中のため、カロリーや量は大人とは異なる方法で評価する必要があります。10代向けのバージョンを準備中です。それまでDUBIはカロリー、栄養素の配分、プランを計算しません。",
  minorNext: "今すぐ食事プランが必要な場合は、小児科医または栄養の専門家に相談してください。",
  bmiChange: "目標を変更",
};

const RU = {
  title: "Прежде чем мы составим ваш план",
  question: "Есть ли у вас какое-либо из следующих состояний или вы соблюдаете лечебную диету, назначенную врачом или диетологом?",
  subtitle: "Если вы ответите «да», DUBI не будет автоматически рассчитывать калории, макронутриенты или составлять план питания.",
  privacy: "DUBI сохраняет только ответ «да/нет», а не само состояние.",
  conditions: {
    pregnancy_or_breastfeeding: "Беременность или грудное вскармливание",
    insulin_treated_diabetes_or_severe_hypoglycaemia: "Диабет на инсулине или повторяющиеся/тяжёлые гипогликемии",
    chronic_kidney_disease_dialysis_transplant_or_renal_restriction: "Хроническая болезнь почек, диализ, пересадка почки или назначенные почечные ограничения",
    eating_disorder_active_suspected_or_recent_treatment: "Текущее или подозреваемое расстройство пищевого поведения или недавнее специализированное лечение",
    bariatric_surgery_with_follow_up: "Бариатрическая операция с продолжающимся наблюдением у специалиста",
    cancer_in_active_treatment_or_cachexia_risk: "Онкологическое заболевание в процессе лечения или риск кахексии/недоедания",
    advanced_liver_disease: "Тяжёлое или декомпенсированное заболевание печени",
    heart_failure_or_prescribed_fluid_sodium_electrolyte_protein_restriction: "Сердечная недостаточность или назначенные ограничения жидкости, натрия, электролитов или белка",
    prescribed_therapeutic_diet: "Лечебная диета, назначенная врачом или диетологом",
    food_anaphylaxis_or_multiple_severe_allergies: "Пищевая анафилаксия в прошлом или несколько тяжёлых пищевых аллергий",
    rapid_unexplained_weight_loss: "Быстрая потеря веса без известной причины",
  },
  answerNo: "Нет, ни одного из этих состояний",
  answerYes: "Да, одно или несколько состояний",
  confirm: "Подтвердить",
  saving: "Сохранение...",
  required: "Выберите ответ, чтобы продолжить.",
  error: "Не удалось сохранить ответ. Проверьте подключение и попробуйте снова.",
  settingsLabel: "Состояния здоровья, требующие специалиста",
  settingsSub: "Обновите ответ, если ваша ситуация изменится.",
  blockTitle: "Для вашей безопасности DUBI не может автоматически составить план.",
  blockBody: "Вы указали состояние, которое требует индивидуальной оценки врача или диетолога. DUBI не меняет лечение, лекарства или клинические ограничения.",
  blockNext: "Обсудите это со специалистом, который вас наблюдает. При наличии конкретных клинических указаний DUBI можно использовать только как помощника в организации.",
  blockAck: "Понятно",
  blockChange: "Моя ситуация изменилась",
  bmiTitle: "При вашем текущем весе DUBI не может составить план для этой цели.",
  bmiBody: "При ИМТ, рассчитанном по вашим данным, дефицит калорий не показан. Вы можете выбрать поддержание веса или набор мышечной массы; рекомендуем консультацию врача или диетолога.",
  bmiLowBody: "По указанным весу и росту ваш ИМТ ниже 17. В этой ситуации перед любым планом питания нужна индивидуальная оценка врача или диетолога.",
  minorTitle: "Пока DUBI не составляет автоматический план питания для пользователей младше 18 лет.",
  minorBody: "В вашем возрасте организм ещё растёт, поэтому калории и порции нужно оценивать иначе, чем у взрослых. Мы готовим версию для подростков; до тех пор DUBI не рассчитывает калории, макронутриенты и не составляет план.",
  minorNext: "Если вам нужен план питания сейчас, обратитесь к педиатру или специалисту по питанию.",
  bmiChange: "Изменить цель",
};

const COPY = { it: IT, en: EN, fr: FR, es: ES, de: DE, ar: AR, pt: PT, zh: ZH, ja: JA, ru: RU };

export function getHighRiskCopy(lang) {
  return COPY[lang] || EN;
}

export const HIGH_RISK_COPY_LANGUAGES = Object.freeze(Object.keys(COPY));
